import os
from django.contrib.gis.utils import LayerMapping
from models import Ward

mapping = {
    "geometry": "POLYGON",
    "f_mnw": "F_MNW", 
    "tot_st": "TOT_ST", 
    "objectid": "OBJECTID", 
    "m_mrg_aglb": "M_MRG_AGLB", 
    "tot_cult": "TOT_CULT", 
    "tot_aglb": "TOT_AGLB", 
    "t_mrg_aglb": "T_MRG_AGLB", 
    "tot_sc": "TOT_SC", 
    "f_mrw": "F_MRW", 
    "f_oth_w": "F_OTH_W", 
    "f_mrg_hh": "F_MRG_HH", 
    "m_pop": "M_POP", 
    "tot_nnw": "TOT_NNW", 
    "m_oth_w": "M_OTH_W", 
    "f_illt": "F_ILLT", 
    "f_pop": "F_POP", 
    "f_st": "F_ST", 
    "m_mrg_cult": "M_MRG_CULT", 
    "m_mrg_hh": "M_MRG_HH", 
    "m_mnw": "M_MNW", 
    "tot_mnw": "TOT_MNW", 
    "f_mrg_cult": "F_MRG_CULT", 
    "m_mfhh": "M_MFHH", 
    "f_mrg_oth": "F_MRG_OTH", 
    "tot_w": "TOT_W", 
    "f_sc": "F_SC", 
    "tot_lit": "TOT_LIT", 
    "t_mrg_cult": "T_MRG_CULT", 
    "m_st": "M_ST", 
    "f_cult": "F_CULT", 
    "f_lit": "F_LIT", 
    "m_mrg_oth": "M_MRG_OTH", 
    "m_aglb": "M_AGLB", 
    "m_cult": "M_CULT", 
    "f_mfhh": "F_MFHH", 
    "f_nnw": "F_NNW", 
    "t_mrg_hh": "T_MRG_HH", 
    "ward_id": "WARD01_ID", 
    "m_sc": "M_SC", 
    "tot_l6": "TOT_L6", 
    "f_aglb": "F_AGLB", 
    "tot_pop": "TOT_POP", 
    "tot_oth_w": "TOT_OTH_W", 
    "m_mrw": "M_MRW", 
    "m_nnw": "M_NNW", 
    "tot_mrw": "TOT_MRW", 
    "tot_nm_hh": "TOT_NM_HH", 
    "ward_name": "WARD_NAME", 
    "t_mrg_oth": "T_MRG_OTH", 
    "f_w": "F_W", 
    "tot_mfhh": "TOT_MFHH", 
    "f_mrg_aglb": "F_MRG_AGLB", 
    "m_w": "M_W", 
    "m_lit": "M_LIT", 
    "tot_illt": "TOT_ILLT"
}

def do(shp_path):
    lm = LayerMapping(Ward, shp_path, mapping,
                      transform=False)
    lm.save(strict=True, verbose=True)
